# Generated by Django 3.2.5 on 2021-07-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210723_0209'),
        ('questions', '0003_auto_20210723_2244'),
    ]

    operations = [
    ]
