# Generated by Django 3.2.5 on 2021-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210725_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default=9, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
    ]
