# Generated by Django 3.2.5 on 2021-07-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
    ]
