# Generated by Django 3.2.5 on 2021-07-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_merge_0002_auto_20210723_0209_0003_auto_20210723_2244'),
        ('answers', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
    ]
