# Generated by Django 3.2.5 on 2021-07-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(default=10, height_field=100, upload_to='profile_images', width_field=100),
            preserve_default=False,
        ),
    ]
